//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFI.MenuCardsAggregator.Services.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RFI.MenuCardsAggregator.Services.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;date&quot;&gt;&lt;div class=&quot;day&quot;&gt;23&lt;/div&gt;&lt;div class=&quot;month&quot;&gt;květen&lt;/div&gt;&lt;/div&gt;&lt;h3 class=&quot;iqGreen mainSectionFont menuDayName&quot;&gt;Pondělí&lt;/h3&gt;&lt;dl class=&quot;menuDayItems&quot;&gt;&lt;dt&gt;&lt;span class=&quot;soupIcon&quot;&gt;&lt;/span&gt;Polévka: 0,33l Podkrkonošské kyselo&lt;/dt&gt;&lt;dd&gt;22,- (&lt;a href=&quot;/img/alergeny_webready.jpg&quot; class=&quot;colorbox&quot;&gt;&lt;span class=&quot;alergeny&quot;&gt;1,3,7&lt;/span&gt;&lt;/a&gt;)&lt;/dd&gt;&lt;dt&gt;&lt;span class=&quot;soupIcon&quot;&gt;&lt;/span&gt;Polévka: 0,33l Polévka z domácího kuřete a kukuřice&lt;/dt&gt;&lt;dd&gt;22,- (&lt;a href=&quot;/img/alergeny_webready.jpg&quot; class=&quot;colorbox&quot;&gt;&lt;span clas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
